program: train_cls.py
method: random
project: brain-stroke-ct
entity: tad537113-university-of-texas
metric:
  name: val_f2_score
  goal: maximize
parameters:
  learning_rate:
    min: 0.0001
    max: 0.005
  batch_size:
    values: [16, 32] 
  dropout_rate:
    values: [0.2, 0.3, 0.4, 0.5]
  label_smoothing:
    min: 0.0
    max: 0.15
  weight_decay:
    min: 0.00001
    max: 0.001
  epochs:
    values: [10, 15, 20]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
